export type Pillar = {
  id: string;
  name: string;
  description: string;
  keywords: string[];
  contentWeight: 'core' | 'supporting' | 'personal';
};

export const PILLARS: Pillar[] = [
  {
    id: 'ai-native-product-engineering',
    name: 'AI-Native Product Engineering',
    description:
      'Practical AI systems for real products: agents, automation, human-in-the-loop workflows, evals, cost, latency, reliability, and product UX.',
    contentWeight: 'core',
    keywords: [
      'ai',
      'ai agents',
      'automation',
      'llm',
      'evals',
      'tool orchestration',
      'human in the loop',
      'ai workflow',
      'inference',
      'latency',
      'token cost',
      'ai reliability',
    ],
  },
  {
    id: 'search-visibility-engineering',
    name: 'Search Visibility Engineering: SEO, AEO & GEO',
    description:
      'Engineering systems that make products discoverable across Google, AI search, LLM answers, structured data, programmatic SEO, and entity-based content.',
    contentWeight: 'core',
    keywords: [
      'seo',
      'aeo',
      'geo',
      'ai search',
      'schema',
      'structured data',
      'crawlability',
      'indexing',
      'programmatic seo',
      'entity optimization',
      'content architecture',
      'search visibility',
    ],
  },
  {
    id: 'marketplace-engineering-pricing',
    name: 'Marketplace Engineering & Pricing Systems',
    description:
      'Designing marketplace systems for liquidity, supply growth, pricing, booking integrity, trust, payments, attribution, and operational reliability.',
    contentWeight: 'core',
    keywords: [
      'marketplace',
      'liquidity',
      'supply growth',
      'dynamic pricing',
      'pricing engine',
      'booking',
      'payments',
      'trust',
      'two-sided marketplace',
      'local marketplace',
      'conversion',
      'attribution',
    ],
  },
  {
    id: 'pragmatic-startup-architecture',
    name: 'Pragmatic Startup Architecture',
    description:
      'Early-stage architecture decisions: modular monoliths, Postgres-first systems, workers, API contracts, reliability, infrastructure tradeoffs, and avoiding premature complexity.',
    contentWeight: 'core',
    keywords: [
      'startup architecture',
      'modular monolith',
      'postgres',
      'workers',
      'system design',
      'api contracts',
      'reliability',
      'state machines',
      'webhooks',
      'infrastructure',
      'technical tradeoffs',
      'overengineering',
    ],
  },
  {
    id: 'modern-web-performance-architecture',
    name: 'Modern Web Performance & Frontend Architecture',
    description:
      'Next.js, React, server rendering, RSC, caching, hydration, payload hygiene, Core Web Vitals, frontend observability, and SEO-performance tradeoffs.',
    contentWeight: 'supporting',
    keywords: [
      'next.js',
      'react',
      'server components',
      'rsc',
      'hydration',
      'ssr',
      'caching',
      'core web vitals',
      'lcp',
      'inp',
      'dto',
      'frontend performance',
    ],
  },
  {
    id: 'analytics-observability-product-truth',
    name: 'Analytics, Observability & Product Truth',
    description:
      'Instrumentation, event taxonomy, attribution, experimentation, RUM, data quality, and using metrics to make better product decisions.',
    contentWeight: 'supporting',
    keywords: [
      'analytics',
      'observability',
      'event taxonomy',
      'instrumentation',
      'attribution',
      'experimentation',
      'ab testing',
      'posthog',
      'ga4',
      'snowplow',
      'bigquery',
      'datadog',
      'rum',
    ],
  },
  {
    id: 'engineering-communication-influence',
    name: 'Engineering Communication & Influence',
    description:
      'How senior engineers create alignment through RFCs, design docs, technical storytelling, stakeholder communication, and decision-making.',
    contentWeight: 'personal',
    keywords: [
      'engineering communication',
      'rfc',
      'design docs',
      'technical storytelling',
      'stakeholder alignment',
      'influence',
      'leadership',
      'async communication',
      'decision making',
    ],
  },
  {
    id: 'global-builder-journey',
    name: 'Global Builder Journey',
    description:
      'Lessons from building a senior engineering career from Colombia into U.S. startups: positioning, interviews, O-1 preparation, public credibility, communication, and leverage.',
    contentWeight: 'personal',
    keywords: [
      'career',
      'senior engineer',
      'staff engineer',
      'immigration',
      'o-1 visa',
      'relocation',
      'latin america',
      'public writing',
      'technical credibility',
      'interviews',
      'positioning',
    ],
  },
];